const FALLBACK={generated_at:null,project:{name:'Project Leverage',overall_progress:0,phases:[]},workers:[],tasks:{queued:0,running:0,completed:0,failed:0,blocked:0},cost:{amount:0,currency:'RM'},sync:{fresh:false},approvals:[],resource_limits:{resources:[]},latest_research:null};
async function getJson(path){const r=await fetch(`${path}?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}
async function loadLiveData(){try{const d=await getJson('./data.json');try{d.resource_limits=await getJson('./resource_limits.json')}catch(e){console.warn('resource limits unavailable',e)}try{d.latest_research=await getJson('./research.json')}catch(e){console.warn('research unavailable',e)}return d}catch(e){console.warn('dashboard state unavailable',e);return FALLBACK}}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderRoadmap(phases){const r=document.getElementById('roadmap');if(!r)return;r.innerHTML=(phases||[]).map((p,i)=>{const x=Math.max(0,Math.min(100,Number(p.progress||0)));return `${i?'<div class="roadmap-line"></div>':''}<div class="roadmap-step ${x>=100?'complete':p.status==='active'?'current':''}"><span class="step-dot">${x>=100?'✓':i+1}</span><div><strong>${esc(p.name)}</strong><small>${esc(p.status||'planned')}</small></div><b>${x}%</b></div>`}).join('')||'<p class="muted">No milestones published.</p>'}
function renderWorkers(ws){const r=document.getElementById('workersList');if(!r)return;r.innerHTML=ws.length?ws.map(w=>`<div class="worker"><div class="avatar ${w.status==='online'?'online':'planned'}">${esc((w.id||'W')[0].toUpperCase())}</div><div class="grow"><strong>${esc(w.id)}</strong><span>${esc(w.role||'')}</span></div><span class="worker-state ${w.status==='online'?'online':'planned'}">${esc(String(w.status||'unknown').toUpperCase())}</span></div>`).join(''):'<p class="muted">No workers registered.</p>'}
function renderLimits(rd){const r=document.getElementById('resourceLimits'),b=document.getElementById('limitOverall');if(!r||!b)return;const a=rd?.resources||[],risk=a.some(x=>['warning','critical'].includes(x.status)),unknown=a.some(x=>x.quota_verified===false||x.status==='unknown_quota_safe_mode');b.textContent=risk?'WARNING':unknown?'SAFE MODE':'MONITORED';b.className=`pill ${risk?'warning-pill':unknown?'blue-pill':'green-pill'}`;r.innerHTML=a.map(x=>`<div class="resource-row"><div class="grow"><strong>${esc(x.provider)}</strong><span>${esc(x.metric)}</span></div><div class="resource-limit"><b>${esc(x.limit)}</b><small>Reset: ${esc(x.reset)}</small></div><span class="pill ${x.status==='safe'?'safe':x.status==='warning'?'warning':unknown?'unknown':'monitor'}">${esc(String(x.status||'monitor').replaceAll('_',' ').toUpperCase())}</span></div>`).join('')||'<p class="muted">No resource policies published.</p>'}
function renderResearch(x){if(!x)return;setText('researchBadge',String(x.status||'unknown').toUpperCase());setText('researchTitle',`${x.asset||'Market'} — ${x.period||'latest'} analysis`);setText('researchMeta',`Research Worker · generated ${x.generated_at?new Date(x.generated_at).toLocaleString():'unknown'}`);setText('researchObs',x.observations??'—');setText('researchVol',x.hourly_volatility==null?'—':`${Number(x.hourly_volatility*100).toFixed(3)}%`);setText('researchEvents',x.large_movement_events??'—');setText('researchReturn',x.average_hourly_return==null?'—':`${Number(x.average_hourly_return*100).toFixed(4)}%`);setText('researchInsight',(x.ai_analysis||'No AI analysis published.').slice(0,650));setText('researchStatus',x.status==='success'?'Completed':String(x.status||'Unknown'))}
function refresh(d){const ws=d.workers||[],t=d.tasks||{},online=ws.filter(w=>w.status==='online').length,p=Number(d.project?.overall_progress||0),fresh=d.sync?.fresh===true;setText('workerCount',ws.length);setText('workerSummary',`${online} active · ${ws.length-online} planned/offline`);setText('workerRegistered',`${ws.length} registered`);setText('taskCount',(t.queued||0)+(t.running||0));setText('taskSummary',`${t.completed||0} completed · ${t.failed||0} failed`);setText('cost',Number(d.cost?.amount||0).toFixed(2));setText('overallProgress',`${p}%`);setText('projectProgress',`${p}%`);const bar=document.getElementById('projectProgressBar');if(bar)bar.style.width=`${p}%`;setText('lastUpdated',d.generated_at?`State synced ${new Date(d.generated_at).toLocaleString()}`:'No sync timestamp');setText('systemStatus',fresh?'ONLINE':'STALE');setText('systemText',fresh?'System online':'Data sync needs attention');setText('activityFresh',fresh?'Live state synchronized':'Data is not confirmed fresh');const ban=document.getElementById('syncBanner');if(ban){ban.style.display=fresh?'none':'block';ban.innerHTML='<strong>⚠ Dashboard is not confirmed current.</strong><p class="muted">Leverage will never label stale state as live.</p>'}renderRoadmap(d.project?.phases||[]);renderWorkers(ws);renderLimits(d.resource_limits);renderResearch(d.latest_research)}
async function updateDashboard(){refresh(await loadLiveData())}document.getElementById('refreshBtn')?.addEventListener('click',updateDashboard);updateDashboard();setInterval(updateDashboard,60000);
