const FALLBACK={generated_at:null,project:{name:'Project Leverage',overall_progress:0,phases:[]},workers:[],tasks:{queued:0,running:0,completed:0,failed:0,blocked:0,cancelled:0},cost:{amount:0,currency:'RM'},sync:{fresh:false},resource_limits:{resources:[]},projects:[]};
const RAW_BASE='https://raw.githubusercontent.com/newbiezzzzz/leverage-system/main/';
async function getJson(path){const r=await fetch(`${RAW_BASE}${path}?live=${Date.now()}`,{cache:'no-store',mode:'cors'});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}
async function loadLiveData(){try{const d=await getJson('dashboard/data.json');try{const w=await getJson('control_plane/workers.json');d.workers=w.workers||[]}catch(e){}try{d.resource_limits=await getJson('dashboard/resource_limits.json')}catch(e){}return d}catch(e){return FALLBACK}}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderRoadmap(phases){const r=document.getElementById('roadmap');if(!r)return;r.innerHTML=(phases||[]).map((p,i)=>{const x=Math.max(0,Math.min(100,Number(p.progress||0)));return `${i?'<div class="roadmap-line"></div>':''}<div class="roadmap-step ${x>=100?'complete':p.status==='active'?'current':''}"><span class="step-dot">${x>=100?'✓':i+1}</span><div><strong>${esc(p.name)}</strong><small>${esc(p.status||'planned')}</small></div><b>${x}%</b></div>`}).join('')||'<p class="muted">No milestones published.</p>'}
function renderWorkers(ws){const r=document.getElementById('workersList');if(!r)return;r.innerHTML=ws.length?ws.map(w=>`<div class="worker"><div class="avatar ${w.status==='online'?'online':'planned'}">${esc((w.id||'W')[0].toUpperCase())}</div><div class="grow"><strong>${esc(w.id)}</strong><span><b>Role:</b> ${esc(w.role||'Unassigned')}</span><small>Projects: ${esc(Array.isArray(w.projects)?w.projects.join(', '):'—')} · Risk: ${esc(w.risk_level||'unspecified')}</small></div><span class="worker-state ${w.status==='online'?'online':'planned'}">${esc(String(w.status||'unknown').toUpperCase())}</span></div>`).join(''):'<p class="muted">No workers registered.</p>'}
function limitInfo(x){const usage=x.used??x.observed_usage??x.usage_value,lim=x.limit??x.limit_value,has=Number.isFinite(Number(usage))&&Number.isFinite(Number(lim))&&Number(lim)>0,rem=x.remaining??(has?Math.max(0,Number(lim)-Number(usage)):null);return{usage,lim,rem}}
function resourceRole(p){return p==='GitHub'?'Code repository & API infrastructure':p==='Gemini'?'AI provider':p==='GitHub Actions'?'Automation execution infrastructure':p==='GitHub Pages'?'Dashboard hosting infrastructure':'Infrastructure resource'}
function renderLimits(rd){const r=document.getElementById('resourceLimits');if(!r)return;const a=rd?.resources||[];setText('quotaChecked',`Live resource snapshot: ${rd?.generated_at?new Date(rd.generated_at).toLocaleString():'unknown'} · ${a.length} resources monitored`);r.innerHTML=a.map(x=>{const q=limitInfo(x),unknown=x.quota_verified===false||x.status==='unknown_quota_safe_mode',p=x.provider||'Unknown',remaining=q.rem===null?(p==='GitHub Pages'?'HOSTING':p==='GitHub Actions'?'NOT EXPOSED':'UNKNOWN'):q.rem,label=unknown?(p==='GitHub Pages'?'HOSTING':'SAFE MODE'):(x.status==='safe'?'LIVE':String(x.status||'MONITOR').toUpperCase());return `<details class="resource-card"><summary><span class="resource-icon">${p.includes('GitHub')?'◈':'✦'}</span><span class="resource-name"><strong>${esc(p)}</strong><small>${esc(x.metric||'Resource')}</small></span><span class="resource-remaining"><b>${esc(remaining)}</b><small>${q.rem===null?'state':'remaining'}</small></span><span class="pill ${unknown?'blue-pill':'green-pill'}">${label}</span></summary><div class="resource-detail"><div><span>Role</span><b>${esc(resourceRole(p))}</b></div><div><span>Used</span><b>${q.usage==null?'—':q.usage}</b></div><div><span>Limit</span><b>${q.lim==null?'Not exposed':q.lim}</b></div><div><span>Remaining</span><b>${q.rem==null?'Not exposed':q.rem}</b></div><div><span>Reset</span><b>${esc(x.reset_at??'Not reported')}</b></div><p>${unknown?'Quota not verified. Safe Mode prevents invented numbers.':'Live provider quota verified.'}</p></div></details>`}).join('')||'<p class="muted">No resource policies published.</p>'}
function renderSystemWorkers(ws){const r=document.getElementById('systemWorkers');if(!r)return;const all=[{id:'Leverage AI Worker (ChatGPT)',role:'AI Manager / Project Coordinator',status:'online',risk_level:'controlled',projects:['Project Leverage'],quota:'Account quota not exposed to the dashboard'}].concat(ws||[]);r.innerHTML=all.map((w,i)=>`<div class="system-worker"><div class="system-avatar ${w.status==='online'?'online':'planned'}">${i===0?'AI':esc((w.id||'W')[0].toUpperCase())}</div><div class="grow"><strong>${esc(w.id)}</strong><span><b>Role:</b> ${esc(w.role||'Unassigned')}</span><small>Projects: ${esc(Array.isArray(w.projects)?w.projects.join(', '):'Project Leverage')} · Risk: ${esc(w.risk_level||'unspecified')}</small></div><div class="system-meta"><b>${esc(String(w.status||'unknown').toUpperCase())}</b><small>${esc(i===0?w.quota:'Worker resource policy monitored')}</small></div></div>`).join('')}
function renderFacts(){const k=document.getElementById('knownFacts'),u=document.getElementById('openQuestions');if(k)k.innerHTML=['Company and project responsibilities are separated.','Workers have explicit capabilities and risk boundaries.','External money movement remains disabled.','The system is designed to remain zero-cost and reversible.'].map(x=>`<div class="fact"><span>✓</span><p>${esc(x)}</p></div>`).join('');if(u)u.innerHTML=['Which project should enter validation next.','Which workers need deeper automation tests.','Which company workflows should become fully autonomous.'].map(x=>`<div class="fact"><span>?</span><p>${esc(x)}</p></div>`).join('');setText('systemBuildProgress','Company OS v1');setText('incomeValidationProgress','Not started');setText('validatedStrategies','—')}
function renderNextMoves(){const n=document.getElementById('nextMoves');if(n)n.innerHTML=[['NOW','Connect project registry, tasks and dashboard as one source of truth'],['NEXT','Validate worker dispatch and lifecycle gates end-to-end'],['THEN','Create a clean project intake → validation workflow'],['AFTER','Select the next zero-cost income project']].map((x,i)=>`<div class="next-move"><span>${i+1}</span><div><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div></div>`).join('')}
function renderBossView(){setText('bossActionTitle','Current situation');setText('bossActionBadge','SYSTEM');setText('bossActionBody','Trading is paused and removed from the active company state. Leverage is now focused on strengthening the reusable company operating system before starting another project.');}
function refresh(d){const ws=d.workers||[],t=d.tasks||{},online=ws.filter(w=>w.status==='online').length,p=Number(d.project?.overall_progress||0),fresh=d.sync?.fresh===true;setText('workerCount',ws.length+1);setText('workerSummary',`${online+1} active · ${ws.length-online} planned/offline`);setText('workerRegistered',`${ws.length} registered + AI Manager`);setText('taskCount',(t.queued||0)+(t.running||0));setText('taskSummary',`${t.completed||0} completed · ${t.failed||0} failed`);setText('cost',Number(d.cost?.amount||0).toFixed(2));setText('overallProgress',`${p}%`);setText('projectProgress',`${p}%`);const bar=document.getElementById('projectProgressBar');if(bar)bar.style.width=`${p}%`;setText('lastUpdated',d.generated_at?`State synced ${new Date(d.generated_at).toLocaleString()}`:'No sync timestamp');setText('systemStatus',fresh?'ONLINE':'STALE');setText('systemText',fresh?'System online':'Data sync needs attention');setText('activityFresh',fresh?'Live state synchronized':'Data is not confirmed fresh');renderRoadmap(d.project?.phases||[]);renderWorkers(ws);renderLimits(d.resource_limits);renderFacts();renderNextMoves();renderBossView();renderSystemWorkers(ws)}
async function updateDashboard(){refresh(await loadLiveData())}document.getElementById('refreshBtn')?.addEventListener('click',updateDashboard);updateDashboard();setInterval(updateDashboard,60000);