const indicators=[
 ['SMA','Trend','Moving-average direction'],['EMA','Trend','Faster trend filter'],['RSI','Momentum','Relative strength'],['MACD','Momentum','Momentum/trend confirmation'],['ROC','Momentum','Rate of change'],['Bollinger Bands','Volatility','Deviation/reversion'],['ATR','Volatility','Range and risk sizing'],['Donchian','Breakout','Channel breakout'],['ADX','Trend','Trend strength'],['Volume','Volume','Participation confirmation'],['Support/Resistance','Price Action','Structure levels'],['Multi-Timeframe','Confirmation','Higher-timeframe filter']
];
const ops=['>','<','crosses above','crosses below','equals'];
const storeKey='leverage_strategies_v1';
const $=id=>document.getElementById(id);
function indicatorOptions(){return indicators.map(x=>`<option value="${x[0]}">${x[0]} — ${x[1]}</option>`).join('')}
function ruleHtml(kind){return `<div class="rule"><div class="field"><label>Indicator / tool</label><select class="ind">${indicatorOptions()}</select></div><div class="field"><label>Condition</label><select class="op">${ops.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Value / indicator</label><input class="val" value="50" placeholder="50 or SMA(50)"></div><button class="pillbtn danger remove">Remove</button></div>`}
function addRule(kind){const target=kind==='entry'?$('entries'):$('exits');target.insertAdjacentHTML('beforeend',ruleHtml(kind));target.lastElementChild.querySelector('.remove').onclick=()=>{target.lastElementChild.remove();refresh()};target.querySelectorAll('input,select').forEach(e=>e.oninput=refresh);refresh()}
function readRules(id){return [...$(id).querySelectorAll('.rule')].map(r=>({indicator:r.querySelector('.ind').value,operator:r.querySelector('.op').value,value:r.querySelector('.val').value}))}
function spec(){return {schema:'leverage-strategy-v1',name:$('name').value.trim()||'Untitled',instrument:$('instrument').value,timeframe:$('timeframe').value,entry_rules:readRules('entries'),exit_rules:readRules('exits'),risk:{position_size_pct:Number($('size').value),stop_loss_pct:Number($('sl').value),take_profit_pct:Number($('tp').value)},metadata:{customer_owned:true,created_at:new Date().toISOString(),status:'draft'}}}
function refresh(){$('spec').textContent=JSON.stringify(spec(),null,2)}
function renderTools(){$('tools').innerHTML=indicators.map(i=>`<div class="tool-card"><strong>${i[0]}</strong><small>${i[1]} · ${i[2]}</small></div>`).join('')}
function renderSaved(){const arr=JSON.parse(localStorage.getItem(storeKey)||'[]');$('saved').innerHTML=arr.length?arr.map((x,i)=>`<button class="pillbtn" data-i="${i}">${x.name} · ${x.instrument} · ${x.timeframe}</button>`).join(''):'<div class="muted-box">No saved strategies yet.</div>';document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>loadSaved(Number(b.dataset.i)))}
function save(){const s=spec();const arr=JSON.parse(localStorage.getItem(storeKey)||'[]');const i=arr.findIndex(x=>x.name===s.name);if(i>=0)arr[i]=s;else arr.push(s);localStorage.setItem(storeKey,JSON.stringify(arr));renderSaved()}
function loadSaved(i){const s=JSON.parse(localStorage.getItem(storeKey)||'[]')[i];if(!s)return;$('name').value=s.name;$('instrument').value=s.instrument;$('timeframe').value=s.timeframe;$('size').value=s.risk.position_size_pct;$('sl').value=s.risk.stop_loss_pct;$('tp').value=s.risk.take_profit_pct;$('entries').innerHTML='';$('exits').innerHTML='';(s.entry_rules||[]).forEach(()=>addRule('entry'));(s.exit_rules||[]).forEach(()=>addRule('exit'));[...$('entries').querySelectorAll('.rule')].forEach((r,j)=>{const v=s.entry_rules[j];r.querySelector('.ind').value=v.indicator;r.querySelector('.op').value=v.operator;r.querySelector('.val').value=v.value});[...$('exits').querySelectorAll('.rule')].forEach((r,j)=>{const v=s.exit_rules[j];r.querySelector('.ind').value=v.indicator;r.querySelector('.op').value=v.operator;r.querySelector('.val').value=v.value});refresh()}
$('addEntry').onclick=()=>addRule('entry');$('addExit').onclick=()=>addRule('exit');$('save').onclick=save;$('clear').onclick=()=>{localStorage.removeItem(storeKey);renderSaved()};$('export').onclick=async()=>{await navigator.clipboard?.writeText(JSON.stringify(spec(),null,2));$('export').textContent='Copied';setTimeout(()=>$('export').textContent='Copy JSON',900)};
['name','instrument','timeframe','size','sl','tp'].forEach(id=>$(id).oninput=refresh);renderTools();addRule('entry');refresh();renderSaved();
