const LW=window.LightweightCharts;const $=id=>document.getElementById(id);const storeKey='leverage_strategies_v1';let rows=[];let chart,candle,volume,sma,ema,rsiChart,rsiLine;let smaOn=false,emaOn=false,rsiOn=false;let replay=false,replayIndex=100,replayTimer=null;
function setStatus(t,cls=''){const e=$('dataStatus');e.textContent=t;e.className='status '+cls}
function toBars(arr){return arr.map(x=>({time:x[0],open:x[1],high:x[2],low:x[3],close:x[4]}))}
function toVol(arr){return arr.map(x=>({time:x[0],value:x[5]}))}
async function loadData(){try{const url='https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1d&limit=500';const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const a=await r.json();rows=a.map(x=>[Math.floor(x[0]/1000),Number(x[1]),Number(x[2]),Number(x[3]),Number(x[4]),Number(x[5])]);setStatus('Live public BTCUSDT · 500 rows','ok');return rows}catch(e){try{const r=await fetch('data/btcusdt_daily.json?v=1',{cache:'no-store'});const a=await r.json();rows=a;setStatus('Fallback research sample · public data route unavailable','warn');return rows}catch(_){setStatus('Data unavailable','warn');return []}}}
function smaCalc(arr,n){const out=[];for(let i=0;i<arr.length;i++){if(i+1<n)continue;let s=0;for(let j=i-n+1;j<=i;j++)s+=arr[j][4];out.push({time:arr[i][0],value:s/n})}return out}
function emaCalc(arr,n){const k=2/(n+1);let e=null;const out=[];for(let i=0;i<arr.length;i++){const c=arr[i][4];if(e===null){if(i+1<n)continue;e=arr.slice(i-n+1,i+1).reduce((a,x)=>a+x[4],0)/n}else e=c*k+e*(1-k);out.push({time:arr[i][0],value:e})}return out}
function rsiCalc(arr,n){let gains=0,losses=0;const out=[];for(let i=1;i<arr.length;i++){const d=arr[i][4]-arr[i-1][4];const g=Math.max(d,0),l=Math.max(-d,0);if(i<=n){gains+=g;losses+=l;if(i===n){let rs=losses?gains/losses:100;out.push({time:arr[i][0],value:100-100/(1+rs)})}}else{gains=(gains*(n-1)+g)/n;losses=(losses*(n-1)+l)/n;let rs=losses?gains/losses:100;out.push({time:arr[i][0],value:100-100/(1+rs)})}}return out}
function makeChart(){const el=$('chart');el.innerHTML='';chart=LW.createChart(el,{layout:{background:{type:'solid',color:'#0f151d'},textColor:'#9aa8ba'},grid:{vertLines:{color:'#18212c'},horzLines:{color:'#18212c'}},crosshair:{mode:LW.CrosshairMode.Normal},rightPriceScale:{borderColor:'#2a3543'},timeScale:{borderColor:'#2a3543',timeVisible:true,secondsVisible:false},autoSize:true});candle=chart.addSeries(LW.CandlestickSeries,{upColor:'#45d483',downColor:'#ef6262',borderVisible:false,wickUpColor:'#45d483',wickDownColor:'#ef6262'});volume=chart.addSeries(LW.HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'volume',color:'#315b80'});chart.priceScale('volume').applyOptions({scaleMargins:{top:0.82,bottom:0}});sma=chart.addSeries(LW.LineSeries,{color:'#5da9ff',lineWidth:2});ema=chart.addSeries(LW.LineSeries,{color:'#ffd166',lineWidth:2});candle.setData(toBars(rows));volume.setData(toVol(rows));chart.timeScale().fitContent();chart.subscribeCrosshairMove(p=>{if(!p||!p.time){$('cursorText').textContent='Move cursor over chart';return}const d=p.seriesData?.get(candle);if(d)$('cursorText').textContent=`O ${d.open.toFixed(2)} · H ${d.high.toFixed(2)} · L ${d.low.toFixed(2)} · C ${d.close.toFixed(2)}`});updateIndicators();}
function updateIndicators(){if(smaOn)sma.setData(smaCalc(rows,20));else sma.setData([]);if(emaOn)ema.setData(emaCalc(rows,50));else ema.setData([]);$('indicatorMetric').textContent=Number(smaOn)+Number(emaOn)+Number(rsiOn);if(rsiOn)showRsi();else hideRsi()}
function showRsi(){if(rsiChart)return;const host=document.createElement('div');host.id='rsiPane';host.style.cssText='height:150px;border-top:1px solid #263241;background:#0f151d';$('chart').appendChild(host);rsiChart=LW.createChart(host,{layout:{background:{type:'solid',color:'#0f151d'},textColor:'#7f8ea1'},grid:{vertLines:{color:'#18212c'},horzLines:{color:'#18212c'}},rightPriceScale:{borderColor:'#2a3543'},timeScale:{visible:false},autoSize:true});rsiLine=rsiChart.addSeries(LW.LineSeries,{color:'#c084fc',lineWidth:2});rsiLine.setData(rsiCalc(rows,14));rsiChart.timeScale().fitContent()}
function hideRsi(){if(rsiChart){rsiChart.remove();rsiChart=null;rsiLine=null}}
function replaySet(i){const s=rows.slice(0,i);candle.setData(toBars(s));volume.setData(toVol(s));if(smaOn)sma.setData(smaCalc(s,20));if(emaOn)ema.setData(emaCalc(s,50));if(rsiOn&&rsiLine)rsiLine.setData(rsiCalc(s,14));$('sourceText').textContent=`Replay · ${s.length}/${rows.length} bars`}
function toggleReplay(){replay=!replay;$('replayBtn').classList.toggle('active',replay);if(replay){replayIndex=Math.min(100,rows.length);replaySet(replayIndex);replayTimer=setInterval(()=>{if(replayIndex>=rows.length){clearInterval(replayTimer);return}replayIndex++;replaySet(replayIndex)},350)}else{clearInterval(replayTimer);candle.setData(toBars(rows));volume.setData(toVol(rows));updateIndicators();$('sourceText').textContent=`Validated research dataset target: ${rows.length} daily rows`}}
function renderStrategies(){const arr=JSON.parse(localStorage.getItem(storeKey)||'[]');$('strategySelect').innerHTML='<option value="">No saved strategy</option>'+arr.map((x,i)=>`<option value="${i}">${x.name} · ${x.instrument} · ${x.timeframe}</option>`).join('');$('strategySelect').onchange=()=>{const x=arr[Number($('strategySelect').value)];$('strategyMetric').textContent=x?x.name:'—'}}
function tabs(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.tabpane').forEach(x=>x.hidden=true);$('tab-'+t.dataset.tab).hidden=false})}
async function boot(){rows=await loadData();if(!rows.length)return;makeChart();renderStrategies();$('smaBtn').onclick=()=>{smaOn=!smaOn;$('smaBtn').classList.toggle('active',smaOn);updateIndicators()};$('emaBtn').onclick=()=>{emaOn=!emaOn;$('emaBtn').classList.toggle('active',emaOn);updateIndicators()};$('rsiBtn').onclick=()=>{rsiOn=!rsiOn;$('rsiBtn').classList.toggle('active',rsiOn);updateIndicators()};$('replayBtn').onclick=toggleReplay;$('resetBtn').onclick=()=>chart.timeScale().fitContent();$('testBtn').onclick=()=>{const x=$('strategySelect').value;if(x===''){$('strategyMetric').textContent='Choose a strategy';return} $('strategyMetric').textContent='Ready to test'};tabs()}
boot();
