const BASE='https://raw.githubusercontent.com/newbiezzzzz/leverage-system/main/';
const LOCAL_API='http://127.0.0.1:8765';
async function getRemote(path){const r=await fetch(`${BASE}${path}?live=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}
function set(id,value){const e=document.getElementById(id);if(e)e.textContent=value}
async function refresh(){try{const company=await getRemote('control_plane/company.json');const projects=await getRemote('control_plane/projects.json');const ledger=await getRemote('control_plane/financial_ledger.json');const active=(projects.projects||[]).filter(p=>!['paused','retired'].includes(p.status));set('companyStage',String(company.company.stage||'system-build').toUpperCase());set('projectCount',projects.projects?.length||0);set('activeProjects',active.length);set('moneyGate',ledger.policy?.live_money_movement?'ENABLED':'PROTECTED')}catch(e){set('companyStage','UNAVAILABLE')}}
async function sendToLocal(payload){const r=await fetch(`${LOCAL_API}/api/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const text=await r.text();throw new Error(text||`local API ${r.status}`)}return r.json()}
const form=document.getElementById('projectForm');
if(form){form.addEventListener('submit',async event=>{event.preventDefault();const name=document.getElementById('projectName').value.trim();const goal=document.getElementById('projectGoal').value.trim();const type=document.getElementById('projectType').value;const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'new-project';const body={project_id:id,name,goal,type,requested_by:'Boss',created_at:new Date().toISOString()};const result=document.getElementById('requestResult');result.hidden=false;result.innerHTML='<p>Sending to Leverage…</p>';try{const reply=await sendToLocal(body);result.innerHTML=`<strong>Project accepted by Leverage.</strong><p><strong>Project ID:</strong> ${reply.project.id}</p><p><strong>Starter tasks:</strong> ${reply.tasks_created}</p><p>The Control Plane has created the project and initial worker workflow.</p>`;form.reset();refresh()}catch(error){localStorage.setItem('leverage:last-project-request',JSON.stringify(body));result.innerHTML='<strong>Leverage Control Plane is offline.</strong><p>The brief was saved locally in this browser, but no company state was changed. Start the Leverage Local API on your PC, then submit again.</p><p><strong>Safety:</strong> the dashboard will not modify company files when the control bridge is offline.</p>'}})}
refresh();setInterval(refresh,60000);
