async function getSnapshot(){const r=await fetch('/api/snapshot',{cache:'no-store'});if(!r.ok)throw new Error(`snapshot ${r.status}`);return (await r.json()).snapshot}
async function getHealth(){const r=await fetch('/api/company-health',{cache:'no-store'});if(!r.ok)throw new Error(`health ${r.status}`);return (await r.json()).health}
async function getReadiness(){const r=await fetch('/api/readiness',{cache:'no-store'});const data=await r.json();return data.readiness}
function set(id,value){const e=document.getElementById(id);if(e)e.textContent=value}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function refresh(){try{const snapshot=await getSnapshot();set('companyStage','SYSTEM');set('projectCount',snapshot.projects);set('activeProjects',snapshot.active_projects);set('moneyGate',snapshot.live_money_movement?'ENABLED':'PROTECTED');const [health,readiness]=await Promise.all([getHealth(),getReadiness()]);set('healthStatus',health.status.toUpperCase());set('readinessStatus',readiness.ready?'READY':'NOT READY');const summary=document.getElementById('healthSummary');const alerts=document.getElementById('healthAlerts');if(summary)summary.textContent=health.alerts.length?`${health.summary.red} critical · ${health.summary.yellow} attention item${health.summary.yellow===1?'':'s'}`:'No attention items detected. Company operating normally.';if(alerts)alerts.innerHTML=health.alerts.length?health.alerts.slice(0,6).map(a=>`<div><strong>${esc(a.severity.toUpperCase())} · ${esc(a.message)}</strong><p>${esc(a.action)}</p></div>`).join(''):'<div><strong>GREEN</strong><p>No action required from Boss right now.</p></div>';const rSummary=document.getElementById('readinessSummary');const rChecks=document.getElementById('readinessChecks');if(rSummary)rSummary.textContent=readiness.ready?'Leverage is structurally ready to begin the next income project.':'Leverage should be strengthened before starting the next income project.';if(rChecks)rChecks.innerHTML=readiness.checks.map(c=>`<div><strong>${esc(c.status.toUpperCase())} · ${esc(c.name)}</strong><p>${esc(c.detail)}</p></div>`).join('')}catch(e){set('companyStage','OFFLINE');set('healthStatus','OFFLINE');set('readinessStatus','OFFLINE');const summary=document.getElementById('healthSummary');if(summary)summary.textContent='Local Control Plane is unavailable.';const rSummary=document.getElementById('readinessSummary');if(rSummary)rSummary.textContent='Release gate could not be evaluated because the local Control Plane is unavailable.'}}
async function sendToLocal(payload){const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const text=await r.text();throw new Error(text||`local API ${r.status}`)}return r.json()}
const form=document.getElementById('projectForm');
if(form){form.addEventListener('submit',async event=>{event.preventDefault();const name=document.getElementById('projectName').value.trim();const goal=document.getElementById('projectGoal').value.trim();const type=document.getElementById('projectType').value;const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'new-project';const payload={project_id:id,name,goal,type,requested_by:'Boss',created_at:new Date().toISOString()};const result=document.getElementById('requestResult');result.hidden=false;result.innerHTML='<p>Sending to Leverage…</p>';try{const reply=await sendToLocal(payload);result.innerHTML=`<strong>Project accepted by Leverage.</strong><p><strong>Project ID:</strong> ${reply.project.id}</p><p><strong>Starter tasks:</strong> ${reply.tasks_created}</p><p>The Control Plane has created the project and initial worker workflow.</p>`;form.reset();refresh()}catch(error){localStorage.setItem('leverage:last-project-request',JSON.stringify(payload));result.innerHTML='<strong>Leverage Control Plane is offline.</strong><p>The brief was saved locally in this browser, but no company state was changed.</p><p><strong>Safety:</strong> the local server is the only component allowed to change company state.</p>'}})}
refresh();setInterval(refresh,60000);
