const MARKETS={
 BTCUSDT:{name:'Bitcoin / USDT',type:'Crypto',priority:'PRIMARY',data:'500 validated daily rows',source:'Binance public market-data service',gates:['READY','NOT TESTED','LOCKED','LOCKED','LOCKED','NOT TRADEABLE'],next:'Start strategy screening'},
 XAUUSDT:{name:'Gold / USDT',type:'Gold',priority:'PRIMARY',data:'Historical source validation pending',source:'Public XAU/USD dataset candidates',gates:['PENDING','NOT TESTED','LOCKED','LOCKED','LOCKED','NOT TRADEABLE'],next:'Verify provenance and ingest'},
 CL:{name:'WTI Crude Oil',type:'Futures',priority:'PRIMARY',data:'Historical source validation pending',source:'Public WTI/CL futures candidates',gates:['PENDING','NOT TESTED','LOCKED','LOCKED','LOCKED','NOT TRADEABLE'],next:'Verify continuous contract and roll handling'},
 FCPO:{name:'FCPO Palm Oil',type:'Futures',priority:'PARALLEL',data:'Zero-cost verifiable history investigation',source:'Public/authorized Bursa-related sources',gates:['PENDING','NOT TESTED','LOCKED','LOCKED','LOCKED','NOT TRADEABLE'],next:'Find legitimate RM0 historical OHLCV'}
};
const labels=['Data','Strategy','Backtest','OOS','Paper','Tradeable'];
const qs=new URLSearchParams(location.search); const target=qs.get('instrument')?.toUpperCase();
function card(id,m){return `<article class="card panel market-detail-card"><div class="panel-head"><div><p class="eyebrow">${id}</p><h2>${m.name}</h2></div><span class="pill ${m.priority==='PRIMARY'?'blue-pill':'green-pill'}">${m.priority}</span></div><div class="metrics"><div><b>${m.gates[0]}</b><span>data</span></div><div><b>${m.gates[1]}</b><span>strategy</span></div><div><b>${m.gates[5]}</b><span>trade readiness</span></div><div><b>RM 0</b><span>capital deployed</span></div></div><div class="market-gates">${labels.map((label,i)=>`<div class="gate-row ${m.gates[i]==='READY'?'gate-ready':m.gates[i]==='PENDING'?'gate-pending':'gate-locked'}"><span>${i+1}</span><strong>${label}</strong><b>${m.gates[i]}</b></div>`).join('')}</div><div class="insight"><span>NEXT ACTION</span><div><strong>${m.next}</strong><p>${m.data}. A market cannot become tradeable until every gate passes.</p></div></div></article>`}
function boot(){const ids=target&&MARKETS[target]?[target]:Object.keys(MARKETS);document.getElementById('title').textContent=target&&MARKETS[target]?MARKETS[target].name:'Choose your market';document.getElementById('marketCards').innerHTML=ids.map(id=>card(id,MARKETS[id])).join('');if(target){document.getElementById('detail').style.display='block';document.getElementById('detail').innerHTML='<div class="panel-head"><div><p class="eyebrow">CUSTOMER RULE</p><h2>Data → Strategy → Backtest → OOS → Paper → Tradeable</h2></div></div><p class="muted">Only evidence moves a market forward. BTCUSDT has passed the initial data gate with 500 validated daily rows; the strategy gate remains untested.</p>'}}
boot();
