async function get(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()}
const METRICS_URL='https://raw.githubusercontent.com/newbiezzzzz/leverage-system/main/control_plane/project_metrics.json';
const TYPES_URL='https://raw.githubusercontent.com/newbiezzzzz/leverage-system/main/control_plane/project_types.json';
const PUBLIC_METRICS_URL='https://leverage-tools.pages.dev/api/public-metrics';
async function getJson(url,label){const r=await fetch(`${url}?live=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${label} ${r.status}`);return r.json()}
async function getMetrics(){return getJson(METRICS_URL,'project_metrics')}
async function getTypes(){return getJson(TYPES_URL,'project_types')}
async function getPublicMetrics(){const r=await fetch(PUBLIC_METRICS_URL,{cache:'no-store'});if(!r.ok)throw new Error(`public_metrics ${r.status}`);return (await r.json()).metrics||{}}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function metricValue(v,suffix=''){return v===null||v===undefined?'UNKNOWN':`${esc(v)}${suffix}`}
function metricCard(label,value,detail,klass=''){return `<div class="card stat ${klass}"><span>${esc(label)}</span><strong>${value}</strong><small>${esc(detail)}</small></div>`}
function renderMetrics(data,preferredId,publicMetrics={}){const root=document.getElementById('metricsList'),state=document.getElementById('metricsState');if(!root)return;const p=data?.projects?.[preferredId]||data?.projects?.['digital-products']||data?.projects?.['engineering-quote-toolkit'];if(!p&&!publicMetrics?.storage_configured){if(state)state.textContent='NO DATA';root.innerHTML='<p class="muted">No verified traffic record is available for P-001 yet.</p>';return}const t=p?.traffic||{},f=p?.funnel||{},r=p?.revenue||{};const live=publicMetrics?.storage_configured===true;const events=live?publicMetrics.events:f.public_tool_events;const pageViews=live?publicMetrics.page_views:t.product_page_views;const visitors=live?publicMetrics.unique_visitors:t.unique_visitors;const quoteEvents=live?publicMetrics.calculated_quotes:f.calculator_events;const clicks=live?publicMetrics.pro_clicks:f.outbound_product_clicks;const conversion=live?publicMetrics.click_through_rate:f.conversion_rate;if(state)state.textContent=live?'LIVE · PUBLIC':'NOT CONNECTED';const sources=(live?publicMetrics.traffic_sources:t.sources)||[];const source=(sources.length?sources.map(x=>`${esc(x.name||x.source||'Source')}: ${esc(x.views??x.metric??'metric')}`).join(' · '):'No traffic sources verified yet');root.innerHTML=`<div class="grid stats">${metricCard('Public page views',metricValue(pageViews),'Live Cloudflare telemetry')}${metricCard('Unique visitors',metricValue(visitors),'Live verified visitor count')}${metricCard('Tool events',metricValue(events),'Public fabrication-tool activity')}${metricCard('Calculator events',metricValue(quoteEvents),'Quote interactions recorded')}</div><div class="strategy-summary"><div><strong>Traffic status</strong><p>${live?'connected':'not connected'}</p></div><div><strong>Measurement source</strong><p>${esc(live?(publicMetrics.measurement_source||'Leverage public telemetry'):(t.measurement_source||'Not connected'))}</p></div><div><strong>Traffic sources</strong><p>${source}</p></div><div><strong>Product clicks</strong><p>${metricValue(clicks)}</p></div><div><strong>Conversion</strong><p>${conversion==null?'UNKNOWN':`${Number(conversion).toFixed(2)}%`}</p></div><div><strong>Verified revenue</strong><p>USD ${Number(r.verified_revenue_usd||0).toFixed(2)} verified</p></div><div><strong>Next gate</strong><p>${esc(p?.interpretation?.next_gate||'Measure traffic, acquire the first buyer, then evaluate conversion and iterate.')}</p></div></div><p class="muted" style="margin-top:12px">Safety rule: unknown traffic is not treated as zero. Public telemetry is usage evidence, not revenue.</p>`}
function typeInfo(types,p){const key=String(p.type||'').replaceAll('-','_');const t=types?.types?.[key]||types?.types?.[p.type];return {label:t?.label||p.type||'Unclassified',channels:t?.channels||[],delivery:t?.delivery||[],events:t?.revenue_events||[]}}
function projectNumber(projects,p){return p?.project_no||`P-${String(projects.findIndex(x=>x.id===p.id)+1).padStart(3,'0')}`}
function renderRegistry(projects,types){const registry=document.getElementById('projectsList');if(!registry)return;registry.innerHTML=projects.length?projects.map(p=>{const x=typeInfo(types,p);const num=projectNumber(projects,p);return `<a href="project-detail.html?id=${encodeURIComponent(p.id)}" class="worker" style="text-decoration:none;color:inherit;display:flex;align-items:center"><div class="avatar ${p.status==='paused'?'planned':'online'}">${esc((p.name||'P')[0].toUpperCase())}</div><div class="grow"><strong>${esc(num)} · ${esc(p.name)}</strong><span><b>Type:</b> ${esc(x.label)} · <b>Stage:</b> ${esc(p.lifecycle_stage||p.status)}</span><small>${esc(p.description||'No description')}</small><small>P-001 may contain multiple digital products; acquisition assets remain inside the project.</small><small><b>Open full project detail →</b></small></div><span class="worker-state ${p.status==='paused'?'planned':'online'}">${esc(String(p.status||'unknown').toUpperCase())}</span></a>`}).join(''):'<p class="muted">No projects registered.</p>'}
async function refresh(){try{const [snapshot,projectsReply,metrics,types,publicMetrics]=await Promise.all([get('/api/snapshot'),get('/api/projects'),getMetrics(),getTypes(),getPublicMetrics()]);const projects=projectsReply.projects||[];const p001=projects.find(p=>p.id==='digital-products')||projects[0];const countEl=document.getElementById('projectCount');const revenueEl=document.getElementById('revenueCount');const payoutEl=document.getElementById('payoutCount');const approvalEl=document.getElementById('approvalCount');const stageEl=document.getElementById('companyStage');const moneyEl=document.getElementById('moneyGate');if(stageEl)stageEl.textContent='SYSTEM OPERATING';if(countEl)countEl.textContent=projects.length;if(revenueEl)revenueEl.textContent=projects.filter(p=>p.revenue_status&&p.revenue_status!=='none').length;if(payoutEl)payoutEl.textContent=snapshot.payouts_prepared;if(approvalEl)approvalEl.textContent='See gates';if(moneyEl)moneyEl.textContent=snapshot.live_money_movement?'ENABLED':'BLOCKED';renderMetrics(metrics,p001?.id,publicMetrics);renderRegistry(projects,types);const gateResults=await Promise.all(projects.map(async p=>{try{return (await get(`/api/projects/${encodeURIComponent(p.id)}/gates`)).report}catch{return null}}));const decisions=document.getElementById('decisionList');if(decisions){const cards=gateResults.filter(Boolean).map(report=>{const gate=report.current_gate;const waiting=gate.status!=='ready';const attention=gate.owner_decision_required?'Owner decision required':(waiting?'Waiting on evidence':'Ready for next gate');const detail=waiting?(gate.reasons||[]).join(' · '):(gate.evidence||[]).join(' · ');return `<div class="worker"><div class="avatar ${gate.status==='ready'?'online':'planned'}">${gate.status==='ready'?'✓':'!'}</div><div class="grow"><strong>${esc(report.project_id)} · ${esc(gate.label)}</strong><span><b>${esc(attention)}</b></span><small>${esc(gate.requires)}${detail?' · '+esc(detail):''}</small></div><span class="worker-state ${gate.status==='ready'?'online':'planned'}">${esc(gate.status.toUpperCase())}</span></div>`}).join('');decisions.innerHTML=cards||'<p class="muted">No project decisions are currently waiting.</p>'}}catch(e){const projects=document.getElementById('projectsList');if(projects)projects.innerHTML='<p class="muted">Local project registry unavailable.</p>';const decisions=document.getElementById('decisionList');if(decisions)decisions.innerHTML='<p class="muted">Local decision center unavailable.</p>';const m=document.getElementById('metricsList');if(m)m.innerHTML='<p class="muted">Project metrics unavailable.</p>';const s=document.getElementById('metricsState');if(s)s.textContent='UNAVAILABLE'}}
refresh();setInterval(refresh,30000);
